### ISSUE TITLE
Pipeline failing due to unsatsfiable classes in go-gaf

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#723]
taxonomy appears incoherent:

![image](https://user-images.githubusercontent.com/50745/43428931-a09e5186-9415-11e8-9df8-148e373cf325.png)

**Comment by cmungall** [comment]
OLS (which has latest):

![image](https://user-images.githubusercontent.com/50745/43429279-68a73138-9417-11e8-82a3-ab6ce4f03c1a.png)

OntoBee (as an older version)

![image](https://user-images.githubusercontent.com/50745/43429289-7a76c39c-9417-11e8-992e-c6804b611f1f.png)


this confirms superimposition of 2 releases is the cause

**Comment by cmungall** [comment]
Very odd, when I load go-gaf I just see the one parent:

![image](https://user-images.githubusercontent.com/50745/43429570-f645ec18-9418-11e8-9684-c340293ce3a9.png)

**Comment by cmungall** [comment]
This will make it much easier to debug this kind of thing:

https://github.com/ontodev/robot/pull/324

**Comment by ukemi** [comment]
But in the ontology we have this:
<img width="1304" alt="taxon_view" src="https://user-images.githubusercontent.com/11067494/43458030-a549331e-9496-11e8-9f3c-9d310896f260.png">

**Comment by kltm** [comment]
From the `pipeline` gitter, was this expected to have cleared. Pipeline runs today still have this failing.

**Comment by kltm** [comment]
Also tagging @balhoff

**Comment by cmungall** [comment]
OK, with the awesome new ROBOT `-D` option on reason we can make a debug module and drill right down to it

one axiom from taxslim:

![image](https://user-images.githubusercontent.com/50745/43493739-51546ff0-94e4-11e8-8209-9cab20c753e3.png)

the others from go-taxon-groupings (which is merged into go-plus)
![image](https://user-images.githubusercontent.com/50745/43493749-6298bf14-94e4-11e8-969d-eed2a2c24f89.png)

so a regen of go-taxon-groupings will fix this.. however, snapshot has to succeed for this fix to make it out there..

**Comment by cmungall** [comment]
Current status:

This PR should fix the issue
https://github.com/geneontology/go-ontology/pull/16173

However, the PR needs to actually be published, which will not happen so long as snapshot fails. So deadlock.

The deadlock should be resolved by relaxing the constraint that owltools executes gaf checks on release runs

**Comment by dougli1sqrd** [comment]
Just to update what was on the gitter channel earlier today: 
I'm still seeing the same thing when I grab the dumped owl file. I see:
- Formicoidae disjoint with Vespoidea is defined in taxslim-disjoint-over-in-taxon.owl
- Formicidae subClassOf Formicoidae is from go-plus and taxslim
- Formicidae SubClassOf Vespoidea is from go-taxon-groupings

**Comment by kltm** [comment]
This has apparently "magically" healed itself.
 None of us can think of a mechanism, except maybe caching along the way at the CDN level (but it didn't /seem/ to be).
