### ISSUE TITLE
Annotation Downloads table needs to be sorted by organism, not group 

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-site#846]
The table that allows users to access annotations (bottom of geneontology.github.io/_docs/download-go-annotations.md, which links to http://current.geneontology.org/products/pages/downloads.html)
is currently sorted by the group (MGI, etc.) not by organism (mouse), and doesn't necessarily have a human-recognisable name.  Priority to be changed for new site & usability. Currently says
>    dictyBase (dictybase, Ddis)

Should perhaps be
>   Dictyostelium discoideum (maintained by dictybase)

@kltm @thomaspd @pgaudet @lpalbou

**Comment by suzialeksander** [comment]
bumping this, as it's rather important.  @kltm, can we assign this to someone?

**Comment by kltm** [comment]
@suzialeksander Adding to a project for now, but "owners" should prioritize this.

**Comment by kltm** [comment]
Talking to @cmungall , we're going to put a `species_code` mapper into the templating script as a temporary measure until we have separated the input and output aspects of the metadata. See #938

**Comment by kltm** [comment]
Once we take action on this, it will be in "Clearing" until the end of the month.

**Comment by kltm** [comment]
@suzialeksander Starting tomorrow, could you look at http://snapshot.geneontology.org/products/pages/downloads.html and let me know if it is sufficient to move this item forward?

**Comment by suzialeksander** [comment]
Sure,  no problem. I'll check in the afternoon to give time for everything to settle

**Comment by suzialeksander** [comment]
I don't see a difference yet... these were the changes in build #630 correct?

**Comment by kltm** [comment]
CloudFront has been kicked. Should work now.

**Comment by suzialeksander** [comment]
yep, that looks better.  The only outlier I still see is for Gramene, I think this should read 

__Oryza sativa__
Gramene (gramene) 

One question: has the goa_dog_complex.gaf always been so large? Any reason to keep this displayed?

I see it wasn't in the original ticket, but I remember @thomaspd also really wanted the n/a out of the Entity type column- change to gene? I know SGD should be gene, looks like SGN should be gene, but I opened the pseudocap file and it has proteins with a few ncRNAs mixed in... 

Do you want to close this ticket and open another to fix the n/a, or leave this open and see if I can dig up the previously proposed solution? (n/a wasn't as high of a priority as fixing the species/db names.)

**Comment by kltm** [comment]
`gramene_oryza` is a metadata issue, so the issue would be in go-site or could be edited in the metadata directly. Similarly, I'm guessing that the n/a's are just related to the `entity_type` in the metadata. Fixes to these are not directly related to this item maybe (metadata changes, etc.), so unless there are still release blockers, I'd vote for new tickets and moving this on.

**Comment by suzialeksander** [comment]
Found the ticket for entity type: https://github.com/geneontology/go-site/issues/847
 'gramene_oryza' display name: https://github.com/geneontology/go-site/issues/981
